version: "3"
services:
  nginx:
    depends_on:
      - backend
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    environment:
      PORT: 80
    ports:
      - "80:80"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      API_KEY: AIzaSyBaoHWlgW3IV0o9zDc-jBIlsCkqK9qvB4s

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
